`Jest`를 사용해서 비동기 로직 테스트 중 `async/await` 구문을 사용하자 아래와 같은 에러를 보게 되었다.

```js
// test-util.spec.js
describe('test util test', () => {
  test('test a', async () => {
    await import('./test-util').then(m => expect(m.default.a()).toBe('a'));
  });
});
```
![테스트 실패](https://images.velog.io/images/motiveko/post/ca763cc9-d4d9-4f26-9153-76b647342f88/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202022-01-07%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%205.56.29.png)

원인은 `import`,`export` 구문 사용을 위해 아래와 같이 `babel-jest`의 `transform`을 설정했는데, 바벨이 `async/await` 코드를 `generator`기반으로 바꾸는데, 이 때 자바스크립트 타겟 레벨이 `es6` 미만이 되면 `generator`를 `regeneratorRuntime` 모듈을 사용해서 구현한다.

이 `regeneratorRuntime` 가 없어서 발생한 에러다.

```json
// jest.config.js
module.exports = {
  ...
  transform: {
    '^.+\\.js$': 'babel-jest',
    '^.+\\.mjs$': 'babel-jest'
  }
};
```
해결 방법은 예전엔 `babel-polyfill`을 추가하는 것이었는데, [`babel-polyfill`은 deprecated ](https://babeljs.io/docs/en/babel-polyfill) 되었고, `regeneratorRuntime`를 사용하면 된다고 한다.

```bash
npm i --save-dev regenerator-runtime
```
```js
import 'regenerator-runtime';

describe('test util test', () => {
  test('test a', async () => {
    await import('./test-util').then(m => expect(m.default.a()).toBe('a'));
  });
});
```

![테스트 성공](https://images.velog.io/images/motiveko/post/3a29b4f7-f3d6-4a79-a85d-b927d0db5a31/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA%202022-01-07%20%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE%205.55.57.png)

